"""
Agentic RAG graph for AlignAgent.

Flow:
  generate_queries → retrieve → grade_docs → [web_search?] → generate_report
                                                    ↑               ↓
                                                 retrieve  ←    reflect
                                                                    ↓
                                                              save_report → END

Key agentic patterns used:
  1. Dynamic query generation  — LLM writes its own retrieval queries
  2. Multi-query retrieval     — several queries per workspace, deduplicated
  3. Document grading (CRAG)   — irrelevant chunks filtered before the LLM sees them
  4. Web search fallback       — kicks in when local docs are too sparse
  5. Self-reflection loop      — agent audits its own report; retries if ungrounded
"""

from __future__ import annotations

import json
import logging
import os
import re
import time
from typing import List, TypedDict

from dotenv import load_dotenv
from langchain_core.documents import Document
from langchain_groq import ChatGroq
from langgraph.graph import END, StateGraph
from tenacity import (
    retry,
    retry_if_exception,
    stop_after_attempt,
    wait_exponential,
    before_sleep_log,
)

from ingestion import MultiTenantIngestionPipeline
from skill_gap_analyzer import SkillGapAnalyzer

load_dotenv()

logger = logging.getLogger(__name__)
if not logger.handlers:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")


# ── State ─────────────────────────────────────────────────────────────────────

class AgentState(TypedDict):
    candidate_id: str
    internship_id: str
    analysis_report_path: str
    # Dynamic queries generated by the LLM
    candidate_queries: List[str]
    internship_queries: List[str]
    # Docs after retrieval and after grading
    candidate_docs: List[Document]
    internship_docs: List[Document]
    # Formatted text passed to the report generator
    candidate_context: str
    internship_context: str
    # Optional web search supplement
    web_context: str
    # Report output
    raw_report: str
    # Enriched resources per missing skill (added after report generation)
    resources: dict
    # Reflection state
    grounding_passed: bool
    retry_count: int


# ── Shared LLM ────────────────────────────────────────────────────────────────

def _llm() -> ChatGroq:
    return ChatGroq(
        model=os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile"),
        temperature=0.2,
        groq_api_key=os.getenv("GROQ_API_KEY"),
    )


def _is_rate_limit(exc: BaseException) -> bool:
    msg = str(exc).lower()
    return "429" in msg or "rate limit" in msg or "rate_limit" in msg


@retry(
    retry=retry_if_exception(_is_rate_limit),
    wait=wait_exponential(multiplier=2, min=5, max=65),
    stop=stop_after_attempt(6),
    before_sleep=before_sleep_log(logger, logging.WARNING),
    reraise=True,
)
def _invoke(llm: ChatGroq, prompt: str) -> str:
    """Single LLM call with automatic exponential back-off on Groq 429 errors."""
    return llm.invoke(prompt).content


# ── Helpers ───────────────────────────────────────────────────────────────────

def _parse_json_list(text: str) -> list[str]:
    """Extract a JSON string array from LLM output, stripping code fences."""
    cleaned = re.sub(r"```(?:json)?", "", text).replace("```", "").strip()
    try:
        result = json.loads(cleaned)
        if isinstance(result, list):
            return [str(q) for q in result]
    except Exception:
        pass
    return re.findall(r'"([^"]+)"', text)[:4] or [text.strip()]


def _format_docs(docs: list[Document]) -> str:
    if not docs:
        return "No relevant documents retrieved."
    return "\n\n".join(
        f"[Doc {i} | source={doc.metadata.get('source', 'unknown')}]\n{doc.page_content.strip()}"
        for i, doc in enumerate(docs, 1)
    )


def _multi_query_retrieve(workspace_id: str, queries: list[str]) -> list[Document]:
    """Run every query against the workspace; deduplicate by content prefix."""
    pipeline = MultiTenantIngestionPipeline(workspace_id=workspace_id)
    retriever = pipeline.get_retriever()
    seen, unique = set(), []
    for query in queries:
        try:
            for doc in retriever.invoke(query):
                key = doc.page_content[:120]
                if key not in seen:
                    seen.add(key)
                    unique.append(doc)
        except Exception:
            logger.warning("⚠️  Retrieval failed for query: %s", query)
    return unique


# ── Node 1: Generate Queries ──────────────────────────────────────────────────
# WHY: hardcoded queries miss nuance. The LLM knows what to look for.

def generate_queries_node(state: AgentState) -> dict:
    logger.info("🧠 [1/7] Generating dynamic retrieval queries...")
    llm = _llm()

    candidate_prompt = (
        "Generate 4 specific search queries to retrieve information from a candidate resume.\n"
        "Cover: technical skills, tools/frameworks, projects, education.\n"
        'Return ONLY a JSON array of 4 strings. Example: ["query 1", "query 2", "query 3", "query 4"]'
    )
    internship_prompt = (
        "Generate 4 specific search queries to retrieve information from an internship description.\n"
        "Cover: required skills, tools/frameworks, responsibilities, qualifications.\n"
        'Return ONLY a JSON array of 4 strings. Example: ["query 1", "query 2", "query 3", "query 4"]'
    )

    candidate_queries = _parse_json_list(_invoke(llm, candidate_prompt))
    internship_queries = _parse_json_list(_invoke(llm, internship_prompt))

    logger.info("✅ %d candidate queries, %d internship queries generated.",
                len(candidate_queries), len(internship_queries))
    return {"candidate_queries": candidate_queries, "internship_queries": internship_queries}


# ── Node 2: Retrieve ──────────────────────────────────────────────────────────
# WHY: more targeted queries → broader, more relevant coverage of the workspace.

def retrieve_node(state: AgentState) -> dict:
    logger.info("🔎 [2/7] Multi-query retrieval...")
    candidate_docs = _multi_query_retrieve(state["candidate_id"], state["candidate_queries"])
    internship_docs = _multi_query_retrieve(state["internship_id"], state["internship_queries"])
    logger.info("📚 Retrieved %d candidate docs, %d internship docs.",
                len(candidate_docs), len(internship_docs))
    return {"candidate_docs": candidate_docs, "internship_docs": internship_docs}


# ── Node 3: Grade Documents ───────────────────────────────────────────────────
# WHY: CRAG pattern — filter out off-topic chunks before they confuse the LLM.

def grade_docs_node(state: AgentState) -> dict:
    logger.info("🔬 [3/7] Grading documents for relevance (batched)...")
    llm = _llm()

    def grade(docs: list[Document], topic: str) -> list[Document]:
        if not docs:
            return []
        # Send all docs in a single call — reduces N calls to 1
        doc_block = "\n\n".join(
            f"[Doc {i}]: {doc.page_content[:400]}"
            for i, doc in enumerate(docs)
        )
        prompt = (
            f"Score each document's relevance to '{topic}' from 1 to 5.\n"
            f"Return ONLY a JSON array of integers in order, one per doc.\n"
            f"Example for 3 docs: [4, 2, 5]\n\n{doc_block}"
        )
        try:
            raw = _invoke(llm, prompt)
            arr = re.search(r"\[.*?\]", raw, re.DOTALL)
            scores = json.loads(arr.group()) if arr else []
            if len(scores) != len(docs):
                logger.warning("  Score count mismatch — keeping all %d docs", len(docs))
                return docs
            kept = [doc for doc, score in zip(docs, scores) if int(score) >= 3]
            logger.info("  Graded %d docs → %d kept for '%s'", len(docs), len(kept), topic)
            return kept or docs  # never return empty — keep all if everything filtered
        except Exception:
            return docs  # keep all on any error

    # Cap before batching — beyond 12 docs the prompt grows too large for Groq's TPM limit
    candidate_docs = grade(state["candidate_docs"][:12], "candidate skills and background")
    internship_docs = grade(state["internship_docs"][:12], "internship requirements and skills")

    return {
        "candidate_docs": candidate_docs,
        "internship_docs": internship_docs,
        "candidate_context": _format_docs(candidate_docs),
        "internship_context": _format_docs(internship_docs),
    }


# ── Node 4: Web Search Fallback ───────────────────────────────────────────────
# WHY: if local docs are too sparse, supplement with live web context.

def web_search_node(state: AgentState) -> dict:
    logger.info("🌐 [4/7] Web search fallback (local docs insufficient)...")
    try:
        from langchain_community.tools import DuckDuckGoSearchRun
        search = DuckDuckGoSearchRun()
        results = []
        for q in state["internship_queries"][:2]:
            try:
                results.append(search.invoke(q + " required skills 2024"))
            except Exception:
                pass
        web_context = "\n\n".join(results)
        logger.info("✅ Web search returned %d result(s).", len(results))
    except Exception:
        web_context = ""
        logger.warning("⚠️  Web search unavailable — continuing without it.")
    return {"web_context": web_context}


# ── Node 5: Generate Report ───────────────────────────────────────────────────

def generate_report_node(state: AgentState) -> dict:
    logger.info("📝 [5/7] Generating skill gap report...")
    llm = _llm()

    web_section = (
        f"\n\nAdditional web context:\n{state['web_context']}"
        if state.get("web_context") else ""
    )

    prompt = f"""You are AlignAgent, an internship readiness and skill-gap analyzer.

Compare the candidate evidence against the internship evidence. Be specific, honest,
and practical. Use only the evidence provided — never invent skills.

Return ONLY a valid JSON object with exactly these keys (no extra text, no markdown fences):

{{
  "candidate_summary": "string",
  "internship_summary": "string",
  "matched_skills": ["skill1", "skill2"],
  "missing_skills": ["skill1", "skill2"],
  "learning_plan": [
    {{
      "week": 1,
      "skill": "skill name",
      "goal": "what the candidate should achieve this week",
      "tasks": ["task 1", "task 2", "task 3"],
      "project": "a small hands-on project to cement this skill"
    }}
  ],
  "resources": {{
    "skill name": [
      {{"title": "resource title", "url": "url or empty string", "type": "course|docs|video|book"}}
    ]
  }},
  "timeline_weeks": <total number of weeks as integer>,
  "recommended_projects": ["project 1", "project 2"],
  "readiness_score": <integer 0-100>
}}

Rules:
- One learning_plan entry per missing skill, ordered by priority.
- Each skill gets 1–3 resources in the resources dict. Prefer free resources
  (official docs, YouTube, free courses like fast.ai, Hugging Face, DeepLearning.AI free tier).
- timeline_weeks = total weeks to complete all learning plan items.
- readiness_score = percentage of required skills the candidate already has.

Candidate evidence:
{state["candidate_context"]}

Internship evidence:
{state["internship_context"]}{web_section}""".strip()

    raw_report = _invoke(llm, prompt).strip()
    logger.info("✅ Report generated.")
    return {"raw_report": raw_report}


# ── Node 6: Enrich Resources ─────────────────────────────────────────────────
# WHY: LLM-suggested resource URLs are often hallucinated. Web search finds real ones.

def generate_resources_node(state: AgentState) -> dict:
    logger.info("📚 [6/8] Searching for real learning resources...")
    try:
        from langchain_community.tools import DuckDuckGoSearchRun
        search = DuckDuckGoSearchRun()
    except Exception:
        logger.warning("⚠️  DuckDuckGo unavailable — skipping resource enrichment.")
        return {"resources": {}}

    # Parse missing skills from the raw report
    missing_skills = []
    try:
        cleaned = re.sub(r"```(?:json)?", "", state["raw_report"]).replace("```", "").strip()
        match = re.search(r"\{.*\}", cleaned, re.DOTALL)
        if match:
            data = json.loads(match.group())
            missing_skills = data.get("missing_skills", [])
    except Exception:
        pass

    resources = {}
    llm = _llm()
    for skill in missing_skills[:5]:  # cap at 5 to avoid rate limits
        try:
            result = search.invoke(f"free {skill} course tutorial for beginners site:youtube.com OR site:coursera.org OR site:huggingface.co OR site:fast.ai OR site:docs.python.org")
            extract_prompt = f"""From this web search result about learning "{skill}", extract up to 3 free learning resources.

Search result:
{result[:1500]}

Return ONLY a JSON array (no extra text):
[{{"title": "...", "url": "...", "type": "course|docs|video|book"}}]"""
            raw = _invoke(llm, extract_prompt)
            cleaned = re.sub(r"```(?:json)?", "", raw).replace("```", "").strip()
            arr_match = re.search(r"\[.*\]", cleaned, re.DOTALL)
            if arr_match:
                entries = json.loads(arr_match.group())
                resources[skill] = entries
                logger.info("  ✅ Found %d resource(s) for %s", len(entries), skill)
        except Exception:
            logger.warning("  ⚠️  Resource search failed for: %s", skill)
        time.sleep(2)  # proactive buffer between skill lookups to stay under RPM

    return {"resources": resources}


# ── Node 7: Self-Reflection ───────────────────────────────────────────────────
# WHY: the agent audits its own output; loops back to re-retrieve if hallucinated.

def reflect_node(state: AgentState) -> dict:
    logger.info("🪞 [7/8] Self-reflection: checking report grounding...")
    llm = _llm()

    prompt = f"""You are a strict grounding auditor.
Check if every skill in matched_skills from the report is supported by the candidate evidence.

Report:
{state["raw_report"]}

Candidate evidence:
{state["candidate_context"][:1200]}

Reply ONLY with valid JSON:
{{"grounded": true or false, "issues": "describe any hallucinations, or 'none'"}}"""

    grounding_passed = True
    try:
        raw = _invoke(llm, prompt)
        cleaned = re.sub(r"```(?:json)?", "", raw).replace("```", "").strip()
        # Extract just the JSON object if the model adds prose around it
        match = re.search(r"\{.*\}", cleaned, re.DOTALL)
        if match:
            cleaned = match.group()
        result = json.loads(cleaned)
        grounding_passed = bool(result.get("grounded", True))
        if not grounding_passed:
            logger.warning("⚠️  Reflection issues: %s", result.get("issues", ""))
        else:
            logger.info("✅ Report is grounded — no hallucinations found.")
    except Exception:
        logger.warning("⚠️  Could not parse reflection response — assuming grounded.")

    return {
        "grounding_passed": grounding_passed,
        "retry_count": state.get("retry_count", 0) + 1,
    }


# ── Node 7: Save Report ───────────────────────────────────────────────────────

def save_report_node(state: AgentState) -> dict:
    logger.info("💾 [8/8] Saving report to %s", state["analysis_report_path"])
    analyzer = SkillGapAnalyzer(
        candidate_workspace_id=state["candidate_id"],
        internship_workspace_id=state["internship_id"],
        fallback_only=True,
    )
    try:
        # Extract JSON from raw report (handles prose-wrapped responses)
        cleaned = re.sub(r"```(?:json)?", "", state["raw_report"]).replace("```", "").strip()
        match = re.search(r"\{.*\}", cleaned, re.DOTALL)
        raw = match.group() if match else cleaned

        # Merge web-found resources into the report JSON before parsing
        data = json.loads(raw)
        if state.get("resources"):
            existing = data.get("resources", {})
            existing.update(state["resources"])
            data["resources"] = existing
        raw = json.dumps(data)
        report = analyzer._parse_report(raw)
    except Exception:
        logger.warning("⚠️  JSON parse failed — using fallback report.")
        raw = analyzer._build_fallback_report(
            state["candidate_context"], state["internship_context"]
        )
        report = analyzer._parse_report(raw)

    analyzer.save_report(report, state["analysis_report_path"])
    logger.info("✅ Done. Report saved.")
    return state


# ── Conditional Routing ───────────────────────────────────────────────────────

def route_after_grading(state: AgentState) -> str:
    """Too few docs after grading → web search. Otherwise → generate report."""
    total = len(state["candidate_docs"]) + len(state["internship_docs"])
    if total < 2:
        return "web_search"
    return "generate_report"


def route_after_reflection(state: AgentState) -> str:
    """Grounding failed and retries remain → retrieve again. Otherwise → save."""
    if not state["grounding_passed"] and state.get("retry_count", 0) < 2:
        logger.info("🔁 Retrying retrieval (attempt %d)...", state["retry_count"])
        return "retrieve"
    return "save_report"


# ── Build Graph ───────────────────────────────────────────────────────────────

workflow = StateGraph(AgentState)

workflow.add_node("generate_queries", generate_queries_node)
workflow.add_node("retrieve", retrieve_node)
workflow.add_node("grade_docs", grade_docs_node)
workflow.add_node("web_search", web_search_node)
workflow.add_node("generate_report", generate_report_node)
workflow.add_node("generate_resources", generate_resources_node)
workflow.add_node("reflect", reflect_node)
workflow.add_node("save_report", save_report_node)

workflow.set_entry_point("generate_queries")

workflow.add_edge("generate_queries", "retrieve")
workflow.add_edge("retrieve", "grade_docs")
workflow.add_conditional_edges("grade_docs", route_after_grading, {
    "web_search": "web_search",
    "generate_report": "generate_report",
})
workflow.add_edge("web_search", "generate_report")
workflow.add_edge("generate_report", "generate_resources")
workflow.add_edge("generate_resources", "reflect")
workflow.add_conditional_edges("reflect", route_after_reflection, {
    "retrieve": "retrieve",
    "save_report": "save_report",
})
workflow.add_edge("save_report", END)

app = workflow.compile()
