[server]
maxUploadSize = 5

[browser]
gatherUsageStats = false

[theme]
base = "light"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFF9C4"
textColor = "#000000"
primaryColor = "#FFE000"
font = "sans serif"
